"""
Data models for DionoAutogen AI
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum
from datetime import datetime


class TaskStatus(str, Enum):
    """Task execution status"""
    PLANNING = "planning"
    CODING = "coding"
    TESTING = "testing"
    DEPLOYING = "deploying"
    COMPLETED = "completed"
    FAILED = "failed"


class BuildPlanRequest(BaseModel):
    """Request to generate a build plan"""
    description: str = Field(..., description="Plain English description of what to build")
    project_name: str = Field(..., description="Name of the project")
    requirements: Optional[List[str]] = Field(default=None, description="Specific requirements")
    tech_stack: Optional[List[str]] = Field(default=None, description="Preferred technologies")


class BuildPlanResponse(BaseModel):
    """Build plan generated by the system"""
    project_name: str
    description: str
    steps: List[Dict[str, Any]]
    estimated_time: int  # minutes
    tech_stack: List[str]
    file_structure: Dict[str, Any]


class CodeExecutionRequest(BaseModel):
    """Request to execute code"""
    code: str = Field(..., description="Code to execute")
    language: str = Field(default="python", description="Programming language")
    project_name: str = Field(..., description="Project workspace")
    timeout: Optional[int] = Field(default=60, description="Execution timeout in seconds")


class CodeExecutionResponse(BaseModel):
    """Result of code execution"""
    success: bool
    output: str
    error: Optional[str] = None
    execution_time: float


class DeploymentRequest(BaseModel):
    """Request to deploy an application"""
    project_name: str
    deployment_type: str = Field(default="docker", description="Deployment method")
    config: Optional[Dict[str, Any]] = Field(default=None, description="Deployment configuration")


class DeploymentResponse(BaseModel):
    """Deployment result"""
    success: bool
    deployment_url: Optional[str] = None
    message: str
    logs: Optional[str] = None


class WebSocketMessage(BaseModel):
    """WebSocket message format"""
    type: str  # status, log, error, result
    status: Optional[TaskStatus] = None
    message: str
    data: Optional[Dict[str, Any]] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class CloudProvider(str, Enum):
    """Supported cloud storage providers"""
    GOOGLE_DRIVE = "gdrive"
    DROPBOX = "dropbox"
    ONEDRIVE = "onedrive"


class CloudFile(BaseModel):
    """Cloud file metadata"""
    id: str
    name: str
    size: int
    mime_type: Optional[str] = None
    modified_time: Optional[datetime] = None
    provider: CloudProvider


class UserCredentials(BaseModel):
    """User credentials for cloud providers"""
    provider: CloudProvider
    credentials: Dict[str, Any]


class ProjectInfo(BaseModel):
    """Project information"""
    name: str
    description: str
    created_at: datetime
    updated_at: datetime
    status: TaskStatus
    files: List[str]
    size_mb: float
